### PR TITLE
Allow turning off ssl verification

### PR DESCRIPTION
**Pull request by kurrycat2004**
Added option to turn ssl verification off because i had problems with this before.

### CODE REVIEW

**Comment by pintman** [comment]
This will allow man in the middle attacks.  :(

**Comment by kurrycat2004** [comment]
SSL is on per default. There is just an option to turn it off by setting the config key "verify" to false. I know that man in the middle attacks would be a problem but i dont know an other way how i could make it work if the ssl certificates are old.

**Comment by kurrycat2004** [comment]
The server updated its certificates so i dont have the problem anymore. Im gonna leave this open if someone wants to merge it.

**Comment by pintman** [comment]
Updating the cert would be the only valid option. Therefore I will close
the PR here. However, thanks for your work.

**Pull request closed without merging**
