### PR TITLE
New Version

### PR DESCRIPTION
**Pull request by AugustH**
a lot of work

- all API Calls, excluding dubious getPersonId() 
- include type hints
- a lot of code cleanup (pep8, ...)
- works with 2.7 and 3.4 - 3.7 
- updated version number to 0.1.10

### CODE REVIEW

**Comment by Yepoleb** [comment]
Looks good!

**Comment by Yepoleb** [comment]
Are you able to merge this yourself or are you waiting for me to press the button?

**Comment by AugustH** [comment]
is there anything else to do? how to get read the docs and pypi uptodate?

**Comment by untitaker** [comment]
Please post your pypi username s.t. I can add u

On July 14, 2018 4:27:32 PM GMT+02:00, Gabriel Huber <notifications@github.com> wrote:
>I don't know, maybe @untitaker can help.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/python-webuntis/python-webuntis/pull/19#issuecomment-405026975

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by AugustH** [comment]
AugustH @ PyPI and Readthedocs

is there a mini-howto to follow?

**Comment by untitaker** [comment]
I added you to PyPI. Readthedocs should work by itself. Which howto do you mean?

**Comment by AugustH** [comment]
howto release a package to pypi -- but somehow i worked it out

thanks for the support

**Pull request merged**
